# SayDeck Docker Compose - Fixed version
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Переопределяем настройки для контейнерной среды
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379  # Внутри контейнера Redis слушает на 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure
    volumes:
      - ./uploads:/app/uploads
      # Монтируем исходный код для live reload
      - .:/app
    networks:
      - saydeck_network

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saydeck_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6378:6379"  # Для внешнего доступа с хоста
    networks:
      - saydeck_network

networks:
  saydeck_network:
    driver: bridge

volumes:
  postgres_data: