# SayDeck Docker Compose - Fixed version
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      # Переопределяем настройки для контейнерной среды
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USE_POSTGRES: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - saydeck_network

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saydeck_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --bind 0.0.0.0 --protected-mode no
    ports:
      - "6379:6379"  # Для внешнего доступа с хоста
    networks:
      - saydeck_network

networks:
  saydeck_network:
    driver: bridge

volumes:
  postgres_data: